### ISSUE TITLE
Include a link in the edit summary

### ISSUE THREAD

**Issue by he7d3r** [MusikAnimal/MusikBot#12]
Hi!
I would like to change the summary from

> Informando **mudanças recentes** nos filtros [[Special:AbuseFilter/7|7]] (padrão); [[Special:AbuseFilter/18|18]] (padrão)

to something like

> Informando **[[Special:AbuseFilter/history|mudanças recentes]]** nos filtros [[Special:AbuseFilter/7|7]] (padrão); [[Special:AbuseFilter/18|18]] (padrão)

This allows users to go directly from their watchlist to the list of changes in filters, without having to open a specific filter first and then selecting "View this filter's history".

**Comment by MusikAnimal** [comment]
Added with 81fd5d86399d9113a78a441c4a0500b2f963a7a0 thanks to framawiki :) Note this links to the history for _all_ filters, not just the ones being reported, but I think that's still convenient. We could also change `[[Special:AbuseFilter/7|7]]` to `[[Special:AbuseFilter/history/7|7]]`? I suppose for the purposes of a watchlist, you're more concerned about seeing exactly what changed

**Comment by he7d3r** [comment]
I think framawiki's version is enough, unless the filters are changed frequently, so either way is fine with me. Thanks!

**Comment by MusikAnimal** [comment]
Works for me if it works for you :) Thanks for the suggestion, and again to Framawiki for the PR!

**Comment by nikhilgoswami** [comment]
Go to hell

**Comment by MusHOikAniEmal** [comment]
works for me if it works for your you lol u getting married look at this guys

@FastLizard4 @samtar @ks0stm @l235 @jackmcbarn @deskana @k6ka @stwalkerster @fluffernutter @slakr @datguy @notaspy @pokefan95 @steinsplitter @ksft @oshwah @krenair @earwig @barras @revent @justberry @sagan @snowolf @e @grumble @jianhui67 @tbloemink @allthefoxes @alexz @samwalton9 @logan @niko @idoh @keegan @uyscuti @cyberpower678 @marktraceur @cameron11598
