### ISSUE TITLE
Add "data-sort-value" so that reports can be sorted by "Last hit" and "Last filter edit"

### ISSUE THREAD

**Issue by he7d3r** [MusikAnimal/MusikBot#2]
Apparently, the parser used by the JavaScript code in MediaWiki is not recognizing the dates on the stale filters reports ([en](https://en.wikipedia.org/wiki/User:MusikBot/StaleFilters/Report), [pt](https://pt.wikipedia.org/wiki/User:MusikBot/StaleFilters/Report)).

This can be fixed locally by adding "data-sort-value" as in
https://pt.wikipedia.org/w/index.php?diff=44521996

**Comment by MusikAnimal** [comment]
Should be fixed now. Thanks! Also FYI I think I finally got it set up where I get notifications for issues/pull requests/etc, or else I would have replied here a while ago :)

**Comment by MusHOikAniEmal** [comment]
bitch pls y close

**Comment by MusHOikAniEmal** [comment]
@notaspy @k6ka @justberry @e @steinsplitter @cameron11598 @cyberpower678 @idoh @sagan @grumble @logan @l235 @niko @keegan @marktraceur @slakr @uyscuti @barras @snowolf @samtar @deskana @pokefan95 @ks0stm @jackmcbarn @ksft @krenair @revent @FastLizard4 @samwalton9 @datguy @oshwah @stwalkerster @allthefoxes @earwig @jianhui67 @fluffernutter @alexz @tbloemink

**Comment by MusHOikAniEmal** [comment]
lol :D
