### ISSUE TITLE
Edit the report only if there are changes?

### ISSUE THREAD

**Issue by he7d3r** [MusikAnimal/MusikBot#4]
Maybe the bot should only edit the report page if there are changes in the content?
Currently it does edits which only change the date: https://pt.wikipedia.org/w/index.php?diff=44757024&oldid=44748102

**Comment by MusikAnimal** [comment]
@he7d3r I had thought the same, but worried people would think the report was outdated. I guess I just needed someone to point out how redundant this is. Will fix.

**Comment by he7d3r** [comment]
Maybe the report could have a "purge" link which would force the bot to update the page (only the timestamp if there is no change in the data). This is similar to what [[https://meta.wikimedia.org/wiki/User:ListeriaBot|ListeriaBot]] does.

**Comment by MusikAnimal** [comment]
Oh nice! Yeah the bot can check the "touched" timestamp of the page, and if it has changed since the last run, regenerate the report. Brilliant idea! I am going to adopt this practice for other tasks as well :)

**Comment by MusikAnimal** [comment]
@he7d3r Alright, so as recommended I'm going to add a "purge" link at the top of the report, but also a description of how it works.

So I need a translation of this sentence:
`Purging will force the bot to update the report on it's next run. Otherwise the report is only updated if there is a change in the data.`

**Comment by he7d3r** [comment]
This should be enough:
> Purgar forçará o robô a atualizar o relatório em sua próxima execução. Caso contrário o relatório só será atualizado se houver alguma alteração nos dados.

**Comment by MusikAnimal** [comment]
This should be fixed now. Sorry again for being such a neglectful bot operator =P

**Comment by he7d3r** [comment]
No problem :-)

**Comment by he7d3r** [comment]
@MusikAnimal should the bot still be doing edits like [this](https://pt.wikipedia.org/w/index.php?diff=46880556)?

**Comment by MusikAnimal** [comment]
@he7d3r What about it is unexpected? It looks like there it went from 7 stale filters to 8, so it should update the report given it has new data.

**Comment by he7d3r** [comment]
Oh, right! My bad...

**Comment by MusHOikAniEmal** [comment]
@e @fluffernutter @cameron11598 @ksft @keegan @oshwah @tbloemink @cyberpower678 @grumble @k6ka @marktraceur @allthefoxes @deskana @logan @steinsplitter @revent @uyscuti @krenair @snowolf @sagan @samwalton9 @earwig @FastLizard4 @slakr @alexz @samtar @justberry @pokefan95 @notaspy @datguy @idoh @jackmcbarn @jianhui67 @niko @ks0stm @stwalkerster @l235 @barras

**Comment by MusHOikAniEmal** [comment]
my name is musik musik :DDDDD

**Comment by MusHOikAniEmal** [comment]
SIMON!!
