### ISSUE TITLE
Add missing pt translations

### ISSUE THREAD

**Issue by he7d3r** [MusikAnimal/MusikBot#8]
Looks like we need to translate a few more words:
> [Filtro 136 (novo) — Ações: **translation missing**: pt.(none); Marcas: ativado,**translation missing**: pt.public; Padrão modificado](https://pt.wikipedia.org/w/index.php?title=Usu%C3%A1rio%28a%29:MusikBot/FilterMonitor/Modifica%C3%A7%C3%B5es_recentes&oldid=45489652)

These seems to come from https://github.com/MusikAnimal/MusikBot/blob/b617b09240cbf1831fb334572736ab4098751e5b/tasks/filter_monitor.rb#L141-L156

These are the translations:
* none: nenhuma
* public: público

**Comment by MusikAnimal** [comment]
Yup! I was just going to ask. I've added this and fixed the bot. Thank you!!!

**Comment by MusHOikAniEmal** [comment]
bitch pls y close

**Comment by MusHOikAniEmal** [comment]
@earwig @datguy @krenair @marktraceur @sagan @steinsplitter @jianhui67 @FastLizard4 @uyscuti @ks0stm @deskana @stwalkerster @pokefan95 @k6ka @samwalton9 @keegan @slakr @fluffernutter @niko @barras @revent @e @alexz @snowolf @logan @idoh @oshwah @samtar @ksft @l235 @cameron11598 @notaspy @justberry @allthefoxes @cyberpower678 @grumble @tbloemink @jackmcbarn

**Comment by MusHOikAniEmal** [comment]
fugger

**Comment by MusHOikAniEmal** [comment]
lmao

**Comment by MusHOikAniEmal** [comment]
:DDDD

**Comment by MusHOikAniEmal** [comment]
simon simon
